### ISSUE TITLE
EBU .yuv10 format

### ISSUE THREAD

**Issue by DTL2020** [Asd-g/RawSource_2.6x#3]
EBU release uncompressed test material in the files with .yuv10 extension. Latest official may be download from 
https://tech.ebu.ch/publications/tech3325s . It looks like record of RAW word-stream of 10-bit active part of SDI data (4:2:2) typically in UYVY interleaved sequence. Written as 16 bit 2x8bit bytes words. But no one of 2 mentioned in documentation formats P210 or P216 works well. It reads interleaving of chroma and luma correctly (i.e. it is definitely not separated planes planar recording) but read data is not correct.

**Comment by DTL2020** [comment]
Oh - as I see from microsoft docs https://docs.microsoft.com/en-us/windows/win32/medfound/10-bit-and-16-bit-yuv-video-formats P210 still semi-planar format. It have separated Y plane and interleaved UV planes.
So it looks plugin currently miss Y210/Y216 formats with full-interleaved 4:2:2 YUYV 10 and 16 bits per sample (started with Y sample) and additional may be named U210/U216 and V210/V216 full-interleaved 4:2:2 10 and 16bits per sample started with U and V sample. I think EBU .yuv10 may be close to U210.

**Comment by Asd-g** [comment]
Check [this thread](https://www.avsforum.com/threads/yuv10-file-format.1464631/) and more specifically posts 11 and 16.

**Comment by DTL2020** [comment]
Oh - I read that. It have that convertor to 8-bit but now EBU will release HDR test patterns in > 8 bit. So to have full 10bit importer to Avisynth is good.

I made some quick pull-request but it only can load EBU files and they also looks like have non-intel endian byte order in words. So either we need to name U210le/U210be pix_format or may be better to add new function argument to load any >8bit file formats in little or big endian bytes order.

This is very poor programmically written and not covers any but only EBU format using U210 pix format. And only 10bit input hardcoded (with <<6 bit shift) if 12bit and more for HDR will be needed it looks we need U212 pix format and more arguments to function write_packed_luma_chroma() - like endian order, actual useful low bits in words, YUV words order.

**Comment by Asd-g** [comment]
Wouldn't be more intuitive to use name like UYVY10 instead U210?
Why casting yuv10 to 16-bit output?
[Here](https://pastebin.com/4Mtj5bNu) patch to process luma and chroma at once without casting to 16-bit.

**Comment by DTL2020** [comment]
May be UYVY10 also good. May be add notation about big-endian byte order
like UYVY10be. Or may be add new parameter to plugin about big/little
endian switching for >8bit per component formats. My idea about U210 was an
extention to microsoft Y210 that mean full-interleaved starting with Y
component.

сб, 31 июл. 2021 г., 17:40 Asd-g ***@***.***>:

**Comment by DTL2020** [comment]
About expanding 10 bit to 16: I think all >8bits formats are converted to
16 bit Avisynth format (and also must be in the file as full 16 bit words
little-endian order). I do not know if Avisynth can process 10bit samples.
I even not sure if simple <<6 bitshift is correct for converting U and V to
16bit, but it looks working.

сб, 31 июл. 2021 г., 17:40 Asd-g ***@***.***>:

**Comment by Asd-g** [comment]
Are there .yuv10 le files?

**Comment by DTL2020** [comment]
I still not see .yuv10 le files. But may exist now or in the future because
it is more typical for x86/64 systems byte order.

вс, 1 авг. 2021 г., 5:49 Asd-g ***@***.***>:

**Comment by DTL2020** [comment]
I think it is good to add full family of 10 to 16 bit versions that I hope directly maps in values to internal Avisynth+ colorspaces: 
.yuv12 to CS_YUV422P12
.yuv16 to CS_YUV422P16

It is now small patch like adding few lines to rawsource26.cpp like:
`table["UYVY12BE"]   = make_tuple(VideoInfo::CS_YUV422P12,   U, Y, V, X, 2, write_packed_luma_chroma_16);


table["UYVY12LE"]   = make_tuple(VideoInfo::CS_YUV422P12,   U, Y, V, X, 3, write_packed_luma_chroma_16);


table["UYVY16BE"]   = make_tuple(VideoInfo::CS_YUV422P16,   U, Y, V, X, 2, write_packed_luma_chroma_16);


table["UYVY16LE"]   = make_tuple(VideoInfo::CS_YUV422P16,   U, Y, V, X, 3, write_packed_luma_chroma_16);`

Somewhere listed .yuv16 format : Uncompressed Y'UV 4:2:2, numbered frame files:
 10b: v210, yuv16 (DVS), yuv10 (DVS), yuv10 (Omnitek)   https://procurement-notices.undp.org/view_file.cfm?doc_id=57766

**Comment by DTL2020** [comment]
For some (unknown) reason EBU start to make 4:2:2 >8bit per component planar written files also with big-endian sequence. So I make another small addition for 4:2:2 planar >8bit (but <=16 bit - not included 32bit-float). May be it is good to add most of >8bit  formats as big-endian order too but it require more thinking on the best programming syntax. Example of 4:2:2 planar 16bit be file - https://ebu.io/qc/testmaterial/188/ Its filename directly shows 'yuv422p16be'.
