### ISSUE TITLE
Pipe input?

### ISSUE THREAD

**Issue by Reel-Deal** [Asd-g/RawSource_2.6x#6]
Hi Asd,

First of all, I just want to say thanks for all of your recent work. Very much appreciated. I wanted to know, if not too much trouble to do, would you consider adding the ability for RawSource to accept pipe input like the [VS version](https://github.com/HolyWu/vsrawsource/commit/877039cf46504298b0b650f567fa00c1545ccccc)? FFmpeg has a handful of audio visualization filters not available in AVS or VS, so I usually do an encode of whatever filter I'm using and then load that in AVS. If RawSource would accept pipe input that would save an extra step.

**Comment by Asd-g** [comment]
Hi,

Sorry for the late response. Try the attached version. To read from pipe use `"-"`. Y4M header is required too.

[RawSourcePlus.zip](https://github.com/Asd-g/RawSource_2.6x/files/9229078/RawSourcePlus.zip)

P.S.: Thanks for your work on the avs docs.

**Comment by Reel-Deal** [comment]
Hi,

No worries, thank you for taking the time to look into this.

I guess I had misunderstood how the pipe input works. I assumed that it would be something like ```RawSourcePlus("ffmpeg script")```.  I did get it to work with a 10 second test pattern but when I try encoding the video it just seems to go on forever.

`ffmpeg -f lavfi -i smptebars=duration=10:size=640x360:rate=30 -pix_fmt yuv420p -f yuv4mpegpipe - | ffmpeg -i "C:\test.avs" -c:v libx264 -crf 18 "C:\rawsource_encode.mp4"`

test.avs:

```
RawSourcePlus("-")
Subtitle("IT WORKS")
```

Aside from that, I guess it will not be possible to view the result of the avs script with VDub correct? It would need to be piped to something like ffplay?

**Comment by Asd-g** [comment]
I uploaded new release and now the issue about forever encoding should be fixed.

I almost didn't use VDub (experience almost 0) and cannot help but if it doesn't support some pipe input it cannot be used.

Yes, ffplay is ok for preview.
```
ffmpeg -i input -f yuv4mpegpipe - | avs2yuv64 script.avs - | ffplay -i -
```
x264 encoding:
```
ffmpeg -i input -f yuv4mpegpipe - | avs2yuv64 script.avs - | x264 --demuxer y4m -o ouput -
```
```
ffmpeg -i input -f yuv4mpegpipe - | avs2yuv64 script.avs - | ffmpeg -i - -c:v libx264 output
```
avs2yuv64 can be replaced with avs2pipemod or similar. But using ffmpeg for opening the avs script would lead to garbage output.
```
ffmpeg -i input -f yuv4mpegpipe - | ffmpeg -i script.avs -f yuv4mpegpipe - | ffmpeg -i - -c:v libx264 output
```
You can compare the output from the above command and the one with avs2yuv. The difference at the end of the clips will the most visible.

**Comment by Reel-Deal** [comment]
Hi,

Finally had a chance to test this out and it works with the example above. Thanks for examples also, makes it easier to understand. I have only tried out a test source at the moment, If I encounter any problems I will let you know. Thanks again :)
